name: Deploy Application

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  #  paths:
   #   - 'app/**'  # Only trigger if changes are made to files in the `app` directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow write access to the repository

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 4: Generate a unique tag
      - name: Generate timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: docker build -t pyaephyo28/my-app:${{ env.TIMESTAMP }} ./app

      # Step 6: Push the Docker image
      - name: Push Docker image
        run: docker push pyaephyo28/my-app:${{ env.TIMESTAMP }}

      # Step 7: Update deployment.yaml with the new tag
      - name: Update deployment.yaml
        run: |
          sed -i "s|image: pyaephyo28/my-app:.*|image: pyaephyo28/my-app:${{ env.TIMESTAMP }}|" manifests/deployment.yaml

      # Step 8: Commit and push changes to Git
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifests/deployment.yaml
          git commit -m "Update image tag to ${{ env.TIMESTAMP }}"
          git push "https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git" main

      # Step 9: Reconcile FluxCD
      - name: Reconcile FluxCD
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          flux reconcile kustomization flux-system

